"""empty message

Revision ID: 473aed006b6c
Revises: a1c6f300a09f
Create Date: 2022-10-17 19:01:38.245614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473aed006b6c'
down_revision = 'a1c6f300a09f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'items', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    # ### end Alembic commands ###
