"""init migration

Revision ID: a1c6f300a09f
Revises: 
Create Date: 2022-10-17 16:51:08.106649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c6f300a09f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('your_resource_model')
    op.add_column('order', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('order', sa.Column('create_time', sa.String(length=63), nullable=False))
    op.add_column('order', sa.Column('status', sa.Integer(), nullable=False))
    op.drop_column('order', 'items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('items', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('order', 'status')
    op.drop_column('order', 'create_time')
    op.drop_column('order', 'user_id')
    op.create_table('your_resource_model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=63), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='your_resource_model_pkey')
    )
    # ### end Alembic commands ###
