"""empty message

Revision ID: c676d52c3a1f
Revises: 473aed006b6c
Create Date: 2022-10-18 03:23:53.746428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c676d52c3a1f'
down_revision = '473aed006b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('items_order_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_order_id_fkey', 'items', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###
